// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGyF6oOkoFHIYhmZGktyvFRydqCG67cXk',
    appId: '1:400934075728:web:a20bdf70d4c0ec7607c055',
    messagingSenderId: '400934075728',
    projectId: 'core-pmc-7a16e',
    authDomain: 'core-pmc-7a16e.firebaseapp.com',
    storageBucket: 'core-pmc-7a16e.firebasestorage.app',
    measurementId: 'G-DPHTEPRHTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAShwHbv7WYrxJXW4cLKJvnsUPUcZ8d1LA',
    appId: '1:400934075728:android:478e39aa446a63a207c055',
    messagingSenderId: '400934075728',
    projectId: 'core-pmc-7a16e',
    storageBucket: 'core-pmc-7a16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaTwjWz_PwR3RKeIORXh90lNWzZTWlWNY',
    appId: '1:400934075728:ios:9d2ab93818cac28007c055',
    messagingSenderId: '400934075728',
    projectId: 'core-pmc-7a16e',
    storageBucket: 'core-pmc-7a16e.firebasestorage.app',
    iosBundleId: 'com.corepmc.corePmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaTwjWz_PwR3RKeIORXh90lNWzZTWlWNY',
    appId: '1:400934075728:ios:9d2ab93818cac28007c055',
    messagingSenderId: '400934075728',
    projectId: 'core-pmc-7a16e',
    storageBucket: 'core-pmc-7a16e.firebasestorage.app',
    iosBundleId: 'com.corepmc.corePmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGyF6oOkoFHIYhmZGktyvFRydqCG67cXk',
    appId: '1:400934075728:web:c8a741185a6cf7a507c055',
    messagingSenderId: '400934075728',
    projectId: 'core-pmc-7a16e',
    authDomain: 'core-pmc-7a16e.firebaseapp.com',
    storageBucket: 'core-pmc-7a16e.firebasestorage.app',
    measurementId: 'G-BKJ2KZWX9R',
  );
}
