// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8m6l-kd5OycBXdjOv-Gcvy0IK4IKM_o',
    appId: '1:963319091501:web:861e67cf10e0beb327c3a4',
    messagingSenderId: '963319091501',
    projectId: 'pmc-projects-18ba4',
    authDomain: 'pmc-projects-18ba4.firebaseapp.com',
    storageBucket: 'pmc-projects-18ba4.firebasestorage.app',
    measurementId: 'G-PCL04EKB23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTL0cYSvblWuqRqlPjCTIRuZZnxzZm0M',
    appId: '1:963319091501:android:51a5825e7060d98427c3a4',
    messagingSenderId: '963319091501',
    projectId: 'pmc-projects-18ba4',
    storageBucket: 'pmc-projects-18ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QUn55JgXstv20wjoAZU8bfuMSQUXMo0',
    appId: '1:963319091501:ios:ee2ee4c4866b5c0927c3a4',
    messagingSenderId: '963319091501',
    projectId: 'pmc-projects-18ba4',
    storageBucket: 'pmc-projects-18ba4.firebasestorage.app',
    iosBundleId: 'com.pmcprojects.pmcstaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QUn55JgXstv20wjoAZU8bfuMSQUXMo0',
    appId: '1:963319091501:ios:c186e27e0eb3352127c3a4',
    messagingSenderId: '963319091501',
    projectId: 'pmc-projects-18ba4',
    storageBucket: 'pmc-projects-18ba4.firebasestorage.app',
    iosBundleId: 'com.corepmc.corePmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8m6l-kd5OycBXdjOv-Gcvy0IK4IKM_o',
    appId: '1:963319091501:web:225fa472ade412c127c3a4',
    messagingSenderId: '963319091501',
    projectId: 'pmc-projects-18ba4',
    authDomain: 'pmc-projects-18ba4.firebaseapp.com',
    storageBucket: 'pmc-projects-18ba4.firebasestorage.app',
    measurementId: 'G-10XRNYDWNM',
  );

}